# Generated by Django 4.0.4 on 2022-04-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_postcomment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='backend.postcomment'),
            preserve_default=False,
        ),
    ]
